#!/usr/bin/perl

# adeylab slack workspace slack-cli wrapper

use Getopt::Std; %opt = ();

$die = "

Wrapper to directly post messages and files to the adeylab Slack workspace.
To use this, log into slack in your web browser and go here:

   https://api.slack.com/custom-integrations/legacy-tokens
   
Then click the \"Create Token\" button. You can copy the token and use it
as the option -t, OR, save it in a file called \".slack_token\" in your
home directory that has the token. Be sure to run:

   'chmod 600 .slack_token'

To ensure no one else can read it. The file should have the workspace name
a tab and then the token.   

Usage: adeylab-slack [options] [channel]

Try to avoid special characters in the message. (e.g. !)

Options: (either -F OR -m must be specified)
   -F   [STR]   File to post
   -m   [STR]   Message to post (in double quotes)
   -t   [STR]   Slack token (if not in ~/.slack_token file)
   -w   [STR]   Token to use (default is first)
                (can specify the name of the token, ie workspace
                 or the line number)

";

getopts("F:m:t:w:", \%opt);

if (!defined $ARGV[0] || (!defined $opt{'F'} && !defined $opt{'m'})) {die $die};
if (!defined $opt{'w'}) {$opt{'w'} = 1};

if (defined $opt{'t'}) {
	$token = $opt{'t'};
} elsif (-e "$ENV{'HOME'}/.slack_token") {
	open T, "$ENV{'HOME'}/.slack_token";
	@TOKENS = ("null");
	while ($l = <T>) {
		chomp $l;
		($workspace,$token) = split(/\t/, $l);
		$WORKSPACE_token{$workspace} = $token;
		push @TOKENS, $token;
	}
	close T;
	if (defined $WORKSPACE_token{$opt{'w'}}) {
		$token = $WORKSPACE_token{$opt{'w'}};
	} elsif ($opt{'w'} =~ /\d+/) {
		$token = $TOKENS[$opt{'w'}];
	} else {
		die "\nA workspace or line number is specified that is not valid (option -w)\n";
	}
} else {
	die "\nNo token specified and ~/.slack_token file does not exist!\n";
}

$ARGV[0] =~ s/^#//;

if (defined $opt{'m'}) {
	$slack_command = "curl -F content=\"$opt{'m'}\" -F channels=#$ARGV[0] -F token=$token https://slack.com/api/files.upload";
} elsif (defined $opt{'F'}) {
	$slack_command = "curl -F file=\"$opt{'F'}\" -F channels=#$ARGV[0] -F token=$token https://slack.com/api/files.upload";
}

print "\nSlack curl command: $slack_command\n";

system($slack_command);
print "\n";

exit;