#!/usr/bin/perl

# adeylab slack workspace slack-cli wrapper

use Getopt::Std; %opt = ();

$die = "

Wrapper to directly post messages and files to the adeylab Slack workspace.
To use this, log into slack in your web browser and go here:

   https://api.slack.com/custom-integrations/legacy-tokens
   
Then click the \"Create Token\" button. You can copy the token and use it
as the option -t, OR, save it in a file called \".slack_token\" in your
home directory that has the token. Be sure to run:

   'chmod 600 .slack_token'

To ensure no one else can read it. The file should have the workspace name
a tab and then the token.   

Usage: adeylab-slack [options] [channel]

Try to avoid special characters in the message. (e.g. !)

Options: (at least one of -m or -F must be specified)
   -m   [STR]   Message to post (in double quotes)
   
   -F   [STR]   File to post (overrides -m message)
   -c   [STR]   Initial comment on file (in double quotes)
   -T   [STR]   Title of file (in double quotes)

   -t   [STR]   Slack token (if not in ~/.slack_token file)
   -w   [STR]   Token to use (default is first)
                (can specify the name of the token, ie workspace
                 or the line number)

";

for ($i = 0; $i < @ARGV; $i++) {
	$ARGV[$i] =~ s/^#//;
}

getopts("F:m:t:w:c:T:", \%opt);

if (!defined $ARGV[0] || (!defined $opt{'F'} && !defined $opt{'m'})) {die $die};
if (!defined $opt{'w'}) {$opt{'w'} = 1};

if (defined $opt{'t'}) {
	$token = $opt{'t'};
} elsif (-e "$ENV{'HOME'}/.slack_token") {
	open T, "$ENV{'HOME'}/.slack_token";
	@TOKENS = ("null");
	while ($l = <T>) {
		chomp $l;
		($workspace,$token) = split(/\t/, $l);
		$WORKSPACE_token{$workspace} = $token;
		push @TOKENS, $token;
	}
	close T;
	if (defined $WORKSPACE_token{$opt{'w'}}) {
		$token = $WORKSPACE_token{$opt{'w'}};
	} elsif ($opt{'w'} =~ /\d+/) {
		$token = $TOKENS[$opt{'w'}];
	} else {
		die "\nA workspace or line number is specified that is not valid (option -w)\n";
	}
} else {
	die "\nNo token specified and ~/.slack_token file does not exist!\n";
}

$slack_command = "curl -F token=$token -F channels=#$ARGV[0]";

if (defined $opt{'m'}) {
	$slack_command .= " -F content=\"$opt{'m'}\"";
}

if (defined $opt{'F'}) {
	$slack_command .= " -F file=\@$opt{'F'}";
}

if (defined $opt{'T'}) {
	$slack_command .= " -F title=\"$opt{'T'}\"";
}

if (defined $opt{'c'}) {
	$slack_command .= " -F initial_comment=\"$opt{'c'}\"";
}

$slack_command .= " https://slack.com/api/files.upload";

print "\nSlack curl command: $slack_command\n\n";

system($slack_command);

print "\n";

exit;